package com.microserve.batterytv.data

import com.microserve.batterytv.BuildConfig
import java.io.IOException
import java.time.Duration
import java.time.Instant
import java.time.OffsetDateTime
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONArray
import org.json.JSONObject

/**
 * HTTP client for the Home Assistant REST API.
 *
 * The `ecoworthy_battery` HACS integration exposes each battery as a device with
 * one sensor per telemetry field. This client discovers those sensors, groups
 * them into [BatteryStatus] objects and reads the recorded SOC history:
 *
 * ```
 * sensor.eco_worthy_0b_<device>_state_of_charge
 * sensor.eco_worthy_0b_<device>_voltage
 * sensor.eco_worthy_0b_<device>_current
 * sensor.eco_worthy_0b_<device>_power
 * sensor.eco_worthy_0b_<device>_temperature
 * sensor.eco_worthy_0b_<device>_design_capacity
 * sensor.eco_worthy_0b_<device>_state_of_health
 * sensor.eco_worthy_0b_<device>_problem_code
 * sensor.eco_worthy_0b_<device>_cell_<n>_voltage
 * ```
 *
 * Entity IDs are generated by HA from the BLE device name (e.g.
 * "ECO-WORTHY 0B_7AD5" → `eco_worthy_0b_7ad5`). Discovery matches the
 * entity-id prefix or the sensor friendly name, so renamed IDs keep working.
 */
object ApiClient {

    private const val SUF_SOC = "_state_of_charge"
    private const val SUF_VOLTAGE = "_voltage"
    private const val SUF_CURRENT = "_current"
    private const val SUF_POWER = "_power"
    private const val SUF_TEMP = "_temperature"
    private const val SUF_CAPACITY = "_design_capacity"
    private const val SUF_HEALTH = "_state_of_health"
    private const val SUF_PROBLEM = "_problem_code"

    private val http = OkHttpClient.Builder()
        .connectTimeout(5, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .build()

    private val baseUrl = "http://${BuildConfig.HA_HOST}:${BuildConfig.HA_PORT}"

    private suspend fun getJsonArray(url: String): JSONArray = withContext(Dispatchers.IO) {
        val request = Request.Builder()
            .url(url)
            .header("Authorization", bearer())
            .build()
        http.newCall(request).execute().use { response ->
            if (!response.isSuccessful) {
                val why = when (response.code) {
                    401 -> "Home Assistant rejected the token (401)"
                    404 -> "Home Assistant endpoint not found (404)"
                    else -> "HTTP ${response.code}"
                }
                throw IOException("$why from ${response.request.url}")
            }
            JSONArray(response.body?.string() ?: throw IOException("empty response"))
        }
    }

    private fun bearer(): String {
        val token = BuildConfig.HA_TOKEN
        if (token.isBlank()) {
            throw IOException(
                "Home Assistant token not configured — add haToken=… in tv-dashboard/gradle.properties"
            )
        }
        return "Bearer $token"
    }

    // ---- current telemetry -------------------------------------------------

    suspend fun fetchBatteries(): List<BatteryStatus> {
        val states = getJsonArray("$baseUrl/api/states")
        val list = mutableListOf<BatteryStatus>()
        for (i in 0 until states.length()) {
            val state = states.getJSONObject(i)
            if (isSocSensor(state)) {
                buildBattery(state, states)?.let { list += it }
            }
        }
        return list.sortedBy { it.name.lowercase() }
    }

    private fun isSocSensor(state: JSONObject): Boolean {
        val id = state.optString("entity_id")
        if (!id.endsWith(SUF_SOC)) return false
        if (BuildConfig.HA_ENTITY_PREFIX.isNotBlank() && id.startsWith(BuildConfig.HA_ENTITY_PREFIX)) {
            return true
        }
        val friendly = state.optJSONObject("attributes")?.optString("friendly_name").orEmpty()
        return BuildConfig.HA_BATTERY_MARKER.isNotBlank() && friendly.contains(BuildConfig.HA_BATTERY_MARKER)
    }

    private fun buildBattery(soc: JSONObject, states: JSONArray): BatteryStatus? {
        val id = soc.optString("entity_id")
        val key = id.removePrefix("sensor.").removeSuffix(SUF_SOC)
        if (key.isBlank()) return null
        val prefix = "sensor.$key"

        val bySuffix = mutableMapOf<String, JSONObject>()
        val cells = sortedMapOf<Int, Double>()
        for (i in 0 until states.length()) {
            val s = states.getJSONObject(i)
            val sid = s.optString("entity_id")
            if (!sid.startsWith(prefix)) continue
            val suffix = sid.removePrefix(prefix)
            when {
                suffix == SUF_VOLTAGE -> bySuffix[SUF_VOLTAGE] = s
                suffix == SUF_CURRENT -> bySuffix[SUF_CURRENT] = s
                suffix == SUF_POWER -> bySuffix[SUF_POWER] = s
                suffix == SUF_TEMP -> bySuffix[SUF_TEMP] = s
                suffix == SUF_CAPACITY -> bySuffix[SUF_CAPACITY] = s
                suffix == SUF_HEALTH -> bySuffix[SUF_HEALTH] = s
                suffix == SUF_PROBLEM -> bySuffix[SUF_PROBLEM] = s
                suffix.startsWith("_cell_") && suffix.endsWith(SUF_VOLTAGE) -> {
                    val n = suffix.removePrefix("_cell_").removeSuffix(SUF_VOLTAGE).toIntOrNull()
                    if (n != null) cells[n] = stateDouble(s) ?: Double.NaN
                }
            }
        }

        val friendly = soc.optJSONObject("attributes")?.optString("friendly_name").orEmpty()
        val name = friendly.removeSuffix(" State of charge").ifBlank { key }

        return BatteryStatus(
            address = key,
            name = name,
            lastUpdated = soc.optString("last_updated").ifBlank { soc.optString("last_changed") },
            soc = stateDouble(soc),
            soh = bySuffix[SUF_HEALTH]?.let(::stateDouble),
            voltage = bySuffix[SUF_VOLTAGE]?.let(::stateDouble),
            current = bySuffix[SUF_CURRENT]?.let(::stateDouble),
            powerW = bySuffix[SUF_POWER]?.let(::stateDouble),
            temperature = bySuffix[SUF_TEMP]?.let(::stateDouble),
            capacityAh = bySuffix[SUF_CAPACITY]?.let(::stateDouble),
            health = bySuffix[SUF_HEALTH]?.let(::stateDouble),
            problemCode = bySuffix[SUF_PROBLEM]?.let(::stateDouble)?.toInt(),
            cells = cells.values.filter { !it.isNaN() },
        )
    }

    // ---- history ------------------------------------------------------------

    suspend fun fetchHistory(address: String, range: String): List<HistoryPoint> {
        val socEntity = "sensor.$address$SUF_SOC"
        val start = Instant.now().minus(rangeDuration(range))
        val url = baseUrl.toHttpUrl().newBuilder()
            .addPathSegments("api/history/period")
            .addPathSegment(start.toString())
            .addQueryParameter("filter_entity_id", socEntity)
            .addQueryParameter("minimal_response", "true")
            .addQueryParameter("no_attributes", "true")
            .addQueryParameter("significant_changes_only", "true")
            .build()
            .toString()

        val outer = getJsonArray(url)
        val points = mutableListOf<HistoryPoint>()
        for (i in 0 until outer.length()) {
            val series = outer.getJSONArray(i)
            for (j in 0 until series.length()) {
                val o = series.getJSONObject(j)
                points += HistoryPoint(
                    ts = o.optString("last_changed").ifBlank { o.optString("last_updated") },
                    soc = o.optString("state").toDoubleOrNull(),
                    voltage = null,
                    current = null,
                )
            }
        }
        return points.sortedBy { parseEpoch(it.ts) }
    }

    private fun rangeDuration(range: String): Duration = when (range) {
        "day" -> Duration.ofDays(1)
        "week" -> Duration.ofDays(7)
        else -> Duration.ofHours(1)
    }

    private fun parseEpoch(iso: String): Long = try {
        OffsetDateTime.parse(iso).toInstant().toEpochMilli()
    } catch (_: Exception) {
        Long.MAX_VALUE
    }

    private fun stateDouble(state: JSONObject): Double? {
        val v = state.optString("state")
        return v.toDoubleOrNull()
    }
}

/** Repository boundary between the ViewModel and the network layer. */
class BatteryRepository {
    suspend fun getBatteries(): List<BatteryStatus> = ApiClient.fetchBatteries()

    suspend fun getHistory(address: String, range: String): List<HistoryPoint> =
        ApiClient.fetchHistory(address, range)
}

